version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000/_health"]
      interval: 10s
      retries: 3

  db:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: genesis
    ports:
      - '3306:3306'
    volumes:
      - './data/db:/var/lib/mysql'
